[project]
name = "almond-bot"
version = "0.1.0"
description = "The best way to control Almond Bot"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "aiohttp>=3.11.16",
]

[project.optional-dependencies]
dev = [
    "ipython",
]